name: workflow2
on:
  push:
    branches:
      - main
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: update-readme
        run: |
          echo "AppVersion-1" >> "C:\Users\eorid\git datacontrol\proyectoGit\README.md"
    
  job2:
    runs-on: self-hosted
    needs: job1
    steps:
      - name: validate-dev
        env:
          TOKEN: ${{ secrets.PROD_TOKEN }}
        run: |
          if ($env:TOKEN -eq $env:LOCAL_PROD_TOKEN) {
              Write-Host "Coinciden "
          } else {
              Write-Host "No coinciden "
              exit 1
          }
