name: update-readme

on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop
  workflow_dispatch:

jobs:
  probar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Comparar secret con variable local
        env:
          TOKEN: ${{ secrets.DEV_TOKEN }}
          LOCAL_DEV_TOKEN: ${{ secrets.LOCAL_DEV_TOKEN }}
        run: |
          if ($env:TOKEN -eq $env:LOCAL_PROD_TOKEN) {
              echo "Coinciden"
              echo "Añadida feature: develop/feature" >> README.md
              } else {
              echo "No coinciden"
              exit 1
          }
