name: update-readme
on: [push,pull_request,workflow_dispatch]
    pull_request:
        types:
            [opened, synchronize, reopened]
    branches:
        - develop
jobs:
    probar:
        runs-on: ubuntu-latest
        steps:
            - name: Comparar secret con variable local
              env:
                  TOKEN: ${{ secrets.DEV_TOKEN }}
              run: |
                    if ($env:TOKEN -eq $env:LOCAL_DEV_TOKEN) {
                        Write-Host "Coinciden "
                    } else {
                        Write-Host "No coinciden "
                        exit 1
                    }
                  echo "Añadida feature: develop/feature" >> README.md